apiVersion: v1
kind: Service
metadata:
  labels:
    app: task-canvas-progress-svc
  name: task-canvas-progress-svc
spec:
  type: ClusterIP
  ports:
    - port: 11000
      targetPort: http-port
      name: task-canvas-progress-port
  selector:
    app: task-canvas-progress
