apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: task-canvas-db
build:
  local:
    push: false
    useBuildkit: true
  artifacts:
    - image: task-canvas-progress
      context: ../task-canvas-progress
      docker:
        dockerfile: Dockerfile
manifests:
  helm:
    releases:
      - name: task-canvas-db
        chartPath: helm/task-canvas-db
      - name: elder-things-encyclopedia
        chartPath: helm/elder-things-encyclopedia-db
      - name: task-canvas-api-mock
        chartPath: helm/wiremock
        setValues:
          deployment.name: task-canvas-api-mock
          service.name: task-canvas-api-mock
          service.targetPort: 8080
          service.port: 8081
      - name: task-canvas-progress
        chartPath: helm/task-canvas-progress
        setValues:
          image.repository: task-canvas-progress
          image.tag: latest
          image.imagePullPolicy: Never
profiles:
  - name: local
    activation:
      - command: dev
