apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-canvas-api
  labels:
    app: task-canvas-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-canvas-api
  template:
    metadata:
      labels:
        app: task-canvas-api
    spec:
      containers:
      - name: task-canvas-api
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http-port
            containerPort: {{ .Values.deployment.containerPort }}
        env:
          - name: POSTGRES_HOST
            value: '{{ .Values.taskCanvasApi.POSTGRES_HOST }}'
          - name: POSTGRES_DB
            value: '{{ .Values.taskCanvasApi.POSTGRES_DB }}'
          - name: POSTGRES_USER
            value: '{{ .Values.taskCanvasApi.POSTGRES_USER }}'
          - name: POSTGRES_PASSWORD
            value: '{{ .Values.taskCanvasApi.POSTGRES_PASSWORD }}'
          - name: POSTGRES_PORT
            value: '{{ .Values.taskCanvasApi.POSTGRES_PORT }}'
          - name: GO_PORT
            value: '{{ .Values.taskCanvasApi.GO_PORT }}'
          - name: JWT_SECRET
            value: '{{ .Values.taskCanvasApi.JWT_SECRET }}'