apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-canvas-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-canvas-db
  template:
    metadata:
      labels:
        app: task-canvas-db
    spec:
      containers:
        - name: task-canvas-db
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: db-port
              containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: root
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: autoload-scripts
            - mountPath: /data/sql
              name: init-sql
      volumes:
        - name: autoload-scripts
          configMap:
            name: "task-canvas-db-autoload-scripts"
        - name: init-sql
          configMap:
            name: "task-canvas-db-sql"