apiVersion: v1
kind: Service
metadata:
  labels:
    app: "task-canvas-db-svc"
  name: "task-canvas-db-svc"
spec:
  selector:
    app: task-canvas-db
  type: NodePort
  ports:
  - name: "task-canvas-db-port"
    port: 10080
    targetPort: db-port
