apiVersion: v1
kind: Service
metadata:
  name: task-canvas-web-svc
  labels:
    app: task-canvas-web-svc
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-port
      name: task-canvas-web-port
  selector:
    app: task-canvas-web
