name: ci

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Helm Lint
        run: helm lint helm/task-canvas-db

      - name: Run Helm install
        run: helm install task-canvas-db helm/task-canvas-db --wait

      - name: Run Helm test
        run: helm test task-canvas-db